
# Tables
USERS_TABLE = "users"
DOGS_TABLE = "dogs"
USERS_DOGS_TABLE = "users_dogs"
COLLARS_TABLE = "collars"
FITNESS_TABLE = "fitness"
CARE_INFO_TABLE = "care_info"
FAQ_TABLE = "faq"
NUTRITION_TABLE = "nutrition"
VACCINATIONS_TABLE = "vaccinations"
MEDICAL_RECORDS_TABLE = "medical_records"
PLACES_TABLE = "places"
GOALS_TABLE = "goals"
GOAL_TEMPLATES_TABLE = "goal_templates"
ACTIVITIES_TABLE = "activities"
FAVORITE_PLACES_TABLE = "favorite_places"
NOTIFICATIONS_TABLE = "notifications"

# Columns
USER_ID_COLUMN = "user_id"
DOG_ID_COLUMN = "dog_id"
COLLAR_ID_COLUMN = "collar_id"
STEPS_COLUMN = "steps"
DISTANCE_COLUMN = "distance"
CALORIES_COLUMN = "calories_burned"
FITNESS_DATE_COLUMN = "fitness_date"
VACCINATION_ID_COLUMN = "vaccination_id"
ACTIVITY_ID_COLUMN = "activity_id"
MEDICAL_RECORD_ID_COLUMN = "record_id"
WEIGHT_COLUMN = "weight"
HEIGHT_COLUMN = "height"
GOAL_ID_COLUMN = "goal_id"
TEMPLATE_ID_COLUMN = "template_id"

# http status codes
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_204_STATUS_NO_CONTENT = 204
HTTP_400_BAD_REQUEST = 400
HTTP_404_NOT_FOUND = 404


COLLAR_FITNESS_COUNT_LIMIT = 65535
BATTERY_THRESHOLD = 10
CONNECTED_TO_MOBILE = True
DECEMBER = 12
DEFAULT_TARGET_STEPS = 2000
DAILY_FREQUENCY = "daily"
WEEKLY_FREQUENCY = "weekly"
MONTHLY_FREQUENCY = "monthly"
DISTANCE_CATEGORY = "distance"
SUNDAY = 6
FIRST_OF_MONTH = 1
